; PlatformIO Project Configuration
; AIAA SLI 2024-2025 - Fullscale Flight Computer
;
; Build:  pio run
; Upload: pio run -t upload

[env:fullscale_flight]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    adafruit/Adafruit GPS Library
    adafruit/Adafruit BNO055
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    mikem/RadioHead
