; PlatformIO Project Configuration
; AIAA SLI 2024-2025 - Subscale V2
;
; Build:  pio run
; Upload: pio run -t upload

[env:subscale_v2]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    adafruit/Adafruit SGP30 Sensor
